services:
  db:
    image: postgres:15-alpine
    container_name: eduforge_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eduforge
    ports:
      - "5433:5432"  # 🌟 左边改为 5433，映射到容器内的 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: